# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend/graficos.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_graficos(object):
    def setupUi(self, graficos):
        graficos.setObjectName("graficos")
        graficos.resize(942, 702)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(graficos.sizePolicy().hasHeightForWidth())
        graficos.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(graficos)
        self.gridLayout.setObjectName("gridLayout")
        self.imagen = QtWidgets.QWidget(graficos)
        self.imagen.setObjectName("imagen")
        self.label_2 = QtWidgets.QLabel(self.imagen)
        self.label_2.setGeometry(QtCore.QRect(290, 120, 47, 13))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.imagen, 0, 0, 1, 1)
        self.graf_1 = QtWidgets.QWidget(graficos)
        self.graf_1.setObjectName("graf_1")
        self.label = QtWidgets.QLabel(self.graf_1)
        self.label.setGeometry(QtCore.QRect(340, 120, 47, 13))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.graf_1, 1, 0, 1, 1)

        self.retranslateUi(graficos)
        QtCore.QMetaObject.connectSlotsByName(graficos)

    def retranslateUi(self, graficos):
        _translate = QtCore.QCoreApplication.translate
        graficos.setWindowTitle(_translate("graficos", "graficos"))
        self.label_2.setText(_translate("graficos", "pene"))
        self.label.setText(_translate("graficos", "pene"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    graficos = QtWidgets.QWidget()
    ui = Ui_graficos()
    ui.setupUi(graficos)
    graficos.show()
    sys.exit(app.exec_())
