# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend/interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_interfaz(object):
    def setupUi(self, interfaz):
        interfaz.setObjectName("interfaz")
        interfaz.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(interfaz.sizePolicy().hasHeightForWidth())
        interfaz.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(interfaz)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graficos = QtWidgets.QWidget(self.centralwidget)
        self.graficos.setObjectName("graficos")
        self.horizontalLayout.addWidget(self.graficos)
        self.opciones = QtWidgets.QWidget(self.centralwidget)
        self.opciones.setMinimumSize(QtCore.QSize(314, 0))
        self.opciones.setMaximumSize(QtCore.QSize(314, 16777215))
        self.opciones.setObjectName("opciones")
        self.horizontalLayout.addWidget(self.opciones)
        interfaz.setCentralWidget(self.centralwidget)

        self.retranslateUi(interfaz)
        QtCore.QMetaObject.connectSlotsByName(interfaz)

    def retranslateUi(self, interfaz):
        _translate = QtCore.QCoreApplication.translate
        interfaz.setWindowTitle(_translate("interfaz", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    interfaz = QtWidgets.QMainWindow()
    ui = Ui_interfaz()
    ui.setupUi(interfaz)
    interfaz.show()
    sys.exit(app.exec_())
