# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend/opciones.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_opciones(object):
    def setupUi(self, opciones):
        opciones.setObjectName("opciones")
        opciones.resize(314, 702)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(opciones.sizePolicy().hasHeightForWidth())
        opciones.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(opciones)
        self.gridLayout.setObjectName("gridLayout")
        self.controlador = QtWidgets.QWidget(opciones)
        self.controlador.setObjectName("controlador")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.controlador)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.controlador)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.controlador, 1, 0, 1, 1)
        self.perturbador = QtWidgets.QWidget(opciones)
        self.perturbador.setObjectName("perturbador")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.perturbador)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.perturbador)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.perturbador, 2, 0, 1, 1)

        self.retranslateUi(opciones)
        QtCore.QMetaObject.connectSlotsByName(opciones)

    def retranslateUi(self, opciones):
        _translate = QtCore.QCoreApplication.translate
        opciones.setWindowTitle(_translate("opciones", "opciones"))
        self.label.setText(_translate("opciones", "Controlador"))
        self.label_2.setText(_translate("opciones", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    opciones = QtWidgets.QWidget()
    ui = Ui_opciones()
    ui.setupUi(opciones)
    opciones.show()
    sys.exit(app.exec_())
