# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend/ventana_inicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Inicio(object):
    def setupUi(self, Inicio):
        Inicio.setObjectName("Inicio")
        Inicio.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Inicio.sizePolicy().hasHeightForWidth())
        Inicio.setSizePolicy(sizePolicy)
        Inicio.setWindowTitle("Inicio")
        self.verticalLayout = QtWidgets.QVBoxLayout(Inicio)
        self.verticalLayout.setObjectName("verticalLayout")
        self.texto_inicio = QtWidgets.QLabel(Inicio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.texto_inicio.sizePolicy().hasHeightForWidth())
        self.texto_inicio.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.texto_inicio.setFont(font)
        self.texto_inicio.setAlignment(QtCore.Qt.AlignCenter)
        self.texto_inicio.setObjectName("texto_inicio")
        self.verticalLayout.addWidget(self.texto_inicio)
        self.label = QtWidgets.QLabel(Inicio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.boton_conectar = QtWidgets.QPushButton(Inicio)
        self.boton_conectar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_conectar.sizePolicy().hasHeightForWidth())
        self.boton_conectar.setSizePolicy(sizePolicy)
        self.boton_conectar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.boton_conectar.setAutoFillBackground(False)
        self.boton_conectar.setObjectName("boton_conectar")
        self.verticalLayout.addWidget(self.boton_conectar)
        self.texto_conexion = QtWidgets.QLabel(Inicio)
        self.texto_conexion.setText("")
        self.texto_conexion.setAlignment(QtCore.Qt.AlignCenter)
        self.texto_conexion.setObjectName("texto_conexion")
        self.verticalLayout.addWidget(self.texto_conexion)
        self.boton_continuar = QtWidgets.QPushButton(Inicio)
        self.boton_continuar.setObjectName("boton_continuar")
        self.verticalLayout.addWidget(self.boton_continuar)
        self.boton_salir = QtWidgets.QPushButton(Inicio)
        self.boton_salir.setObjectName("boton_salir")
        self.verticalLayout.addWidget(self.boton_salir)

        self.retranslateUi(Inicio)
        QtCore.QMetaObject.connectSlotsByName(Inicio)

    def retranslateUi(self, Inicio):
        _translate = QtCore.QCoreApplication.translate
        self.texto_inicio.setText(_translate("Inicio", "PROYECTO CAPSTONE CONTROL"))
        self.label.setText(_translate("Inicio", "Asegurate de conectar este PC y la Raspberry al wifi de Alex"))
        self.boton_conectar.setText(_translate("Inicio", "Conectar"))
        self.boton_continuar.setText(_translate("Inicio", "Continuar"))
        self.boton_salir.setText(_translate("Inicio", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Inicio = QtWidgets.QWidget()
    ui = Ui_Inicio()
    ui.setupUi(Inicio)
    Inicio.show()
    sys.exit(app.exec_())
